# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171102_1350'),
        ('account', '0003_userinfo_profile_picture'),
    ]

    operations = [
    ]
